import {
  AnimalPenDef,
  BuildingDef,
  CropDef,
  DecorationDef,
  ItemDef,
  ItemId,
  Recipe,
  Achievement,
  FarmEntity,
} from '../types/game';

export const LEVEL_XP_REQUIREMENTS: number[] = [
  0,     // Level 0 (not used)
  50,    // Level 1 -> 2
  120,   // Level 2 -> 3
  240,   // Level 3 -> 4
  420,   // Level 4 -> 5
  680,   // Level 5 -> 6
  1050,  // Level 6 -> 7
  1550,  // Level 7 -> 8
  2200,  // Level 8 -> 9
  3000,  // Level 9 -> 10
  4000,  // Level 10 -> 11
  5200,  // Level 11 -> 12
  6600,  // Level 12 -> 13
  8200,  // Level 13 -> 14
  10000, // Level 14 -> 15
  12500, // Level 15 -> 16
  16000, // Level 16 -> 17
  20000, // Level 17 -> 18
  25000, // Level 18 -> 19
  32000, // Level 19 -> 20
];

export const ITEMS: Record<ItemId, ItemDef> = {
  // Crops
  wheat: {
    id: 'wheat',
    name: 'Trigo',
    category: 'crop',
    storage: 'silo',
    icon: '🌾',
    basePrice: 3,
    minLevel: 1,
    description: 'Cultura básica e rápida de colheita.',
  },
  corn: {
    id: 'corn',
    name: 'Milho',
    category: 'crop',
    storage: 'silo',
    icon: '🌽',
    basePrice: 7,
    minLevel: 2,
    description: 'Essencial para ração de vacas e pipoca.',
  },
  carrot: {
    id: 'carrot',
    name: 'Cenoura',
    category: 'crop',
    storage: 'silo',
    icon: '🥕',
    basePrice: 10,
    minLevel: 3,
    description: 'Cenoura fresca e crocante.',
  },
  sugarcane: {
    id: 'sugarcane',
    name: 'Cana-de-açúcar',
    category: 'crop',
    storage: 'silo',
    icon: '🎋',
    basePrice: 14,
    minLevel: 3,
    description: 'Doce e essencial para fazer açúcar e xarope.',
  },
  soybean: {
    id: 'soybean',
    name: 'Soja',
    category: 'crop',
    storage: 'silo',
    icon: '🌱',
    basePrice: 18,
    minLevel: 4,
    description: 'Grãos ricos para rações e pratos especiais.',
  },
  pumpkin: {
    id: 'pumpkin',
    name: 'Abóbora',
    category: 'crop',
    storage: 'silo',
    icon: '🎃',
    basePrice: 32,
    minLevel: 6,
    description: 'Abóbora redonda e dourada.',
  },
  apple: {
    id: 'apple',
    name: 'Maçã',
    category: 'crop',
    storage: 'silo',
    icon: '🍎',
    basePrice: 38,
    minLevel: 5,
    description: 'Fruta colhida de macieiras.',
  },

  // Animal products
  egg: {
    id: 'egg',
    name: 'Ovo',
    category: 'animal_product',
    storage: 'barn',
    icon: '🥚',
    basePrice: 18,
    minLevel: 1,
    description: 'Ovo caipira fresco das galinhas.',
  },
  milk: {
    id: 'milk',
    name: 'Leite',
    category: 'animal_product',
    storage: 'barn',
    icon: '🥛',
    basePrice: 32,
    minLevel: 2,
    description: 'Leite cremoso e nutritivo das vacas.',
  },
  bacon: {
    id: 'bacon',
    name: 'Bacon',
    category: 'animal_product',
    storage: 'barn',
    icon: '🥓',
    basePrice: 50,
    minLevel: 5,
    description: 'Bacon defumado dos porcos.',
  },
  wool: {
    id: 'wool',
    name: 'Lã',
    category: 'animal_product',
    storage: 'barn',
    icon: '🧶',
    basePrice: 54,
    minLevel: 7,
    description: 'Lã macia tosquiada das ovelhas.',
  },

  // Feeds
  chicken_feed: {
    id: 'chicken_feed',
    name: 'Ração de Galinha',
    category: 'feed',
    storage: 'barn',
    icon: '🥣',
    basePrice: 7,
    minLevel: 1,
    description: 'Alimento nutritivo para galinhas.',
  },
  cow_feed: {
    id: 'cow_feed',
    name: 'Ração de Vaca',
    category: 'feed',
    storage: 'barn',
    icon: '🌾',
    basePrice: 14,
    minLevel: 2,
    description: 'Alimento balanceado para vacas leiteiras.',
  },
  pig_feed: {
    id: 'pig_feed',
    name: 'Ração de Porco',
    category: 'feed',
    storage: 'barn',
    icon: '🥕',
    basePrice: 20,
    minLevel: 5,
    description: 'Alimento para engorda de porcos.',
  },
  sheep_feed: {
    id: 'sheep_feed',
    name: 'Ração de Ovelha',
    category: 'feed',
    storage: 'barn',
    icon: '☘️',
    basePrice: 24,
    minLevel: 7,
    description: 'Alimento rico para ovelhas produzirem lã.',
  },

  // Bakery
  bread: {
    id: 'bread',
    name: 'Pão Quentinho',
    category: 'food',
    storage: 'barn',
    icon: '🍞',
    basePrice: 21,
    minLevel: 1,
    description: 'Pão rústico crocante assado no forno a lenha.',
  },
  corn_bread: {
    id: 'corn_bread',
    name: 'Pão de Milho',
    category: 'food',
    storage: 'barn',
    icon: '🥖',
    basePrice: 72,
    minLevel: 2,
    description: 'Broa de milho fofinha e dourada.',
  },
  cookie: {
    id: 'cookie',
    name: 'Biscoito Caseiro',
    category: 'food',
    storage: 'barn',
    icon: '🍪',
    basePrice: 104,
    minLevel: 3,
    description: 'Biscoitos doces assados com amor.',
  },
  carrot_pie: {
    id: 'carrot_pie',
    name: 'Torta de Cenoura',
    category: 'food',
    storage: 'barn',
    icon: '🥧',
    basePrice: 130,
    minLevel: 4,
    description: 'Torta farta recheada com cenouras frescas.',
  },
  pizza: {
    id: 'pizza',
    name: 'Pizza Crocante',
    category: 'food',
    storage: 'barn',
    icon: '🍕',
    basePrice: 190,
    minLevel: 7,
    description: 'Pizza de forno com muito queijo.',
  },

  // Dairy
  cream: {
    id: 'cream',
    name: 'Nata / Creme',
    category: 'food',
    storage: 'barn',
    icon: '🍶',
    basePrice: 50,
    minLevel: 3,
    description: 'Creme de leite espesso e aveludado.',
  },
  butter: {
    id: 'butter',
    name: 'Manteiga',
    category: 'food',
    storage: 'barn',
    icon: '🧈',
    basePrice: 82,
    minLevel: 4,
    description: 'Manteiga batida tradicional de fazenda.',
  },
  cheese: {
    id: 'cheese',
    name: 'Queijo Artesanal',
    category: 'food',
    storage: 'barn',
    icon: '🧀',
    basePrice: 122,
    minLevel: 5,
    description: 'Queijo maturado com sabor marcante.',
  },

  // Sugar Mill
  brown_sugar: {
    id: 'brown_sugar',
    name: 'Açúcar Mascavo',
    category: 'food',
    storage: 'barn',
    icon: '🟤',
    basePrice: 32,
    minLevel: 3,
    description: 'Açúcar puro da cana-de-açúcar.',
  },
  white_sugar: {
    id: 'white_sugar',
    name: 'Açúcar Refinado',
    category: 'food',
    storage: 'barn',
    icon: '⚪',
    basePrice: 50,
    minLevel: 4,
    description: 'Açúcar fininho para sobremesas.',
  },
  syrup: {
    id: 'syrup',
    name: 'Xarope Doce',
    category: 'food',
    storage: 'barn',
    icon: '🍯',
    basePrice: 90,
    minLevel: 6,
    description: 'Calda espessa para panquecas e tortas.',
  },

  // BBQ Grill
  pancake: {
    id: 'pancake',
    name: 'Panquecas',
    category: 'food',
    storage: 'barn',
    icon: '🥞',
    basePrice: 108,
    minLevel: 4,
    description: 'Pilha fofa de panquecas grelhadas.',
  },
  bacon_and_eggs: {
    id: 'bacon_and_eggs',
    name: 'Ovos com Bacon',
    category: 'food',
    storage: 'barn',
    icon: '🍳',
    basePrice: 200,
    minLevel: 5,
    description: 'Café da manhã dos campeões da fazenda.',
  },
  burger: {
    id: 'burger',
    name: 'Hambúrguer Caipira',
    category: 'food',
    storage: 'barn',
    icon: '🍔',
    basePrice: 240,
    minLevel: 6,
    description: 'Sanduíche suculento e completo.',
  },

  // Popcorn
  popcorn: {
    id: 'popcorn',
    name: 'Pipoca Simples',
    category: 'food',
    storage: 'barn',
    icon: '🍿',
    basePrice: 32,
    minLevel: 4,
    description: 'Milho estourado quentinho e salgado.',
  },
  butter_popcorn: {
    id: 'butter_popcorn',
    name: 'Pipoca Amanteigada',
    category: 'food',
    storage: 'barn',
    icon: '🧈🍿',
    basePrice: 125,
    minLevel: 5,
    description: 'Pipoca dourada coberta de manteiga da fazenda.',
  },

  // Upgrade items
  wood_plank: {
    id: 'wood_plank',
    name: 'Tábua de Madeira',
    category: 'material',
    storage: 'barn',
    icon: '🪵',
    basePrice: 150,
    minLevel: 1,
    description: 'Material para expandir o celeiro.',
  },
  nail: {
    id: 'nail',
    name: 'Prego',
    category: 'material',
    storage: 'barn',
    icon: '🔩',
    basePrice: 150,
    minLevel: 1,
    description: 'Material para expandir o silo.',
  },
  screw: {
    id: 'screw',
    name: 'Parafuso',
    category: 'material',
    storage: 'barn',
    icon: '🪛',
    basePrice: 150,
    minLevel: 1,
    description: 'Material para melhorias estruturais.',
  },
  bolt: {
    id: 'bolt',
    name: 'Parafuso com Porca',
    category: 'material',
    storage: 'barn',
    icon: '⚙️',
    basePrice: 150,
    minLevel: 1,
    description: 'Material raro para reformas na fazenda.',
  },
  axe: {
    id: 'axe',
    name: 'Machadinha',
    category: 'material',
    storage: 'barn',
    icon: '🪓',
    basePrice: 120,
    minLevel: 1,
    description: 'Ferramenta para limpar árvores velhas.',
  },
  saw: {
    id: 'saw',
    name: 'Serrote',
    category: 'material',
    storage: 'barn',
    icon: '🪚',
    basePrice: 150,
    minLevel: 1,
    description: 'Ferramenta para cortar árvores grandes mortas.',
  },
  dynamite: {
    id: 'dynamite',
    name: 'Dinamite',
    category: 'material',
    storage: 'barn',
    icon: '🧨',
    basePrice: 200,
    minLevel: 1,
    description: 'Explosivo forte para destruir pedras no terreno.',
  },

  // Expansion items
  land_map: {
    id: 'land_map',
    name: 'Escritura de Terra',
    category: 'material',
    storage: 'barn',
    icon: '🗺️',
    basePrice: 400,
    minLevel: 10,
    description: 'Documento necessário para adquirir novos terrenos.',
  },
  marker_stake: {
    id: 'marker_stake',
    name: 'Estaca de Madeira',
    category: 'material',
    storage: 'barn',
    icon: '📍',
    basePrice: 400,
    minLevel: 10,
    description: 'Usada para demarcar os limites da fazenda.',
  },
  brick: {
    id: 'brick',
    name: 'Tijolos',
    category: 'material',
    storage: 'barn',
    icon: '🧱',
    basePrice: 400,
    minLevel: 10,
    description: 'Tijolos de construção duráveis.',
  },

  // Fishing System
  red_lure: {
    id: 'red_lure',
    name: 'Isca Vermelha',
    category: 'material',
    storage: 'barn',
    icon: '🪱',
    basePrice: 15,
    minLevel: 25,
    description: 'Isca padrão para pegar peixes comuns.',
  },
  green_lure: {
    id: 'green_lure',
    name: 'Isca Verde',
    category: 'material',
    storage: 'barn',
    icon: '🐛',
    basePrice: 25,
    minLevel: 25,
    description: 'Isca especial para peixes maiores.',
  },
  fishing_net: {
    id: 'fishing_net',
    name: 'Rede de Pesca',
    category: 'material',
    storage: 'barn',
    icon: '🕸️',
    basePrice: 50,
    minLevel: 25,
    description: 'Garante 3 filés de peixe após 8 horas.',
  },
  shrimp_trap: {
    id: 'shrimp_trap',
    name: 'Armadilha p/ Camarão',
    category: 'material',
    storage: 'barn',
    icon: '🧺',
    basePrice: 80,
    minLevel: 25,
    description: 'Garante 1 camarão após 12 horas.',
  },
  fish_fillet: {
    id: 'fish_fillet',
    name: 'Filé de Peixe',
    category: 'animal_product',
    storage: 'barn',
    icon: '🐟',
    basePrice: 54,
    minLevel: 25,
    description: 'Peixe fresco capturado no lago.',
  },
  salmon: {
    id: 'salmon',
    name: 'Salmão',
    category: 'animal_product',
    storage: 'barn',
    icon: '🍣',
    basePrice: 90,
    minLevel: 25,
    description: 'Peixe nobre do lago profundo.',
  },
  trout: {
    id: 'trout',
    name: 'Truta',
    category: 'animal_product',
    storage: 'barn',
    icon: '🐠',
    basePrice: 75,
    minLevel: 25,
    description: 'Um peixe colorido e ágil.',
  },
  bass: {
    id: 'bass',
    name: 'Robalo',
    category: 'animal_product',
    storage: 'barn',
    icon: '🐟',
    basePrice: 85,
    minLevel: 25,
    description: 'Peixe grande, forte e muito valorizado.',
  },
  catfish: {
    id: 'catfish',
    name: 'Bagre',
    category: 'animal_product',
    storage: 'barn',
    icon: '🦈',
    basePrice: 65,
    minLevel: 25,
    description: 'Vive no fundo barrento do rio.',
  },
  shrimp: {
    id: 'shrimp',
    name: 'Camarão',
    category: 'animal_product',
    storage: 'barn',
    icon: '🦐',
    basePrice: 114,
    minLevel: 25,
    description: 'Capturado com armadilhas.',
  },
  lobster_tail: {
    id: 'lobster_tail',
    name: 'Cauda de Lagosta',
    category: 'animal_product',
    storage: 'barn',
    icon: '🦞',
    basePrice: 150,
    minLevel: 25,
    description: 'Lagosta luxuosa, requer fervura.',
  },
  sushi: {
    id: 'sushi',
    name: 'Sushi de Salmão',
    category: 'food',
    storage: 'barn',
    icon: '🍣🍚',
    basePrice: 180,
    minLevel: 25,
    description: 'Sushi refinado feito com salmão fresco.',
  },
  fish_pie: {
    id: 'fish_pie',
    name: 'Torta de Peixe',
    category: 'food',
    storage: 'barn',
    icon: '🥧🐟',
    basePrice: 150,
    minLevel: 25,
    description: 'Torta saborosa de peixe assada no forno.',
  },
  shrimp_skewer: {
    id: 'shrimp_skewer',
    name: 'Espeto de Camarão',
    category: 'food',
    storage: 'barn',
    icon: '🍢🦐',
    basePrice: 140,
    minLevel: 25,
    description: 'Camarão grelhado suculento.',
  },

  // Bee Tree & Honey
  nectar: {
    id: 'nectar',
    name: 'Néctar Floral',
    category: 'material',
    storage: 'silo',
    icon: '🍯✨',
    basePrice: 24,
    minLevel: 30,
    description: 'Néctar doce e aromático coletado pelas abelhas.',
  },
  honey: {
    id: 'honey',
    name: 'Pote de Mel Puro',
    category: 'food',
    storage: 'barn',
    icon: '🍯',
    basePrice: 160,
    minLevel: 30,
    description: 'Mel puro e dourado centrifugado no Melzeiro.',
  },

  // Mining Tools
  shovel: {
    id: 'shovel',
    name: 'Pá',
    category: 'material',
    storage: 'barn',
    icon: '🥄',
    basePrice: 80,
    minLevel: 24,
    description: 'Ferramenta para escavar sedimentos e pequenos minérios na mina.',
  },
  pickaxe: {
    id: 'pickaxe',
    name: 'Picareta',
    category: 'material',
    storage: 'barn',
    icon: '⛏️',
    basePrice: 120,
    minLevel: 24,
    description: 'Ferramenta de aço para quebrar veios de rocha sólida na mina.',
  },
  tnt_barrel: {
    id: 'tnt_barrel',
    name: 'Barril de TNT',
    category: 'material',
    storage: 'barn',
    icon: '🛢️',
    basePrice: 350,
    minLevel: 24,
    description: 'Barril de alta carga explosiva para detonações massivas na mina.',
  },

  // Mining Ores & Minerals
  coal: {
    id: 'coal',
    name: 'Carvão Mineral',
    category: 'material',
    storage: 'barn',
    icon: '🪨',
    basePrice: 10,
    minLevel: 24,
    description: 'Combustível fóssil rico extraído das profundezas da mina.',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Minério de Ferro',
    category: 'material',
    storage: 'barn',
    icon: '🪙',
    basePrice: 15,
    minLevel: 24,
    description: 'Minério de ferro bruto pronto para fundir em barras resistentes.',
  },
  silver_ore: {
    id: 'silver_ore',
    name: 'Minério de Prata',
    category: 'material',
    storage: 'barn',
    icon: '🔘',
    basePrice: 28,
    minLevel: 27,
    description: 'Minério prateado reluzente de grande nobreza e valor.',
  },
  gold_ore: {
    id: 'gold_ore',
    name: 'Minério de Ouro',
    category: 'material',
    storage: 'barn',
    icon: '✨',
    basePrice: 45,
    minLevel: 30,
    description: 'Pepitas de ouro nativo brilhante para fundir em barras nobres.',
  },

  // Smelted Metal Bars
  iron_bar: {
    id: 'iron_bar',
    name: 'Barra de Ferro',
    category: 'material',
    storage: 'barn',
    icon: '⛓️',
    basePrice: 55,
    minLevel: 24,
    description: 'Lingote forjado na Fundição. Essencial para ferramentas e comércio.',
  },
  silver_bar: {
    id: 'silver_bar',
    name: 'Barra de Prata',
    category: 'material',
    storage: 'barn',
    icon: '🥈',
    basePrice: 95,
    minLevel: 27,
    description: 'Barra nobre de prata fundida, muito procurada por mercadores.',
  },
  gold_bar: {
    id: 'gold_bar',
    name: 'Barra de Ouro',
    category: 'material',
    storage: 'barn',
    icon: '🥇',
    basePrice: 160,
    minLevel: 30,
    description: 'Barra de ouro maciço de altíssimo prestígio e valor no mercado.',
  },
};

export const CROPS: Partial<Record<ItemId, CropDef>> = {
  wheat: {
    id: 'wheat',
    name: 'Trigo',
    growTimeSeconds: 10, // Fast for fun & responsive gameplay!
    harvestYield: 2,
    xp: 2,
    minLevel: 1,
    icon: '🌾',
    color: '#EAB308',
    growStages: ['🌱', '🌿', '🌾'],
  },
  corn: {
    id: 'corn',
    name: 'Milho',
    growTimeSeconds: 25,
    harvestYield: 2,
    xp: 4,
    minLevel: 2,
    icon: '🌽',
    color: '#FACC15',
    growStages: ['🌱', '🌿', '🌽'],
  },
  carrot: {
    id: 'carrot',
    name: 'Cenoura',
    growTimeSeconds: 40,
    harvestYield: 2,
    xp: 7,
    minLevel: 3,
    icon: '🥕',
    color: '#F97316',
    growStages: ['🌱', '🥕', '🥕'],
  },
  sugarcane: {
    id: 'sugarcane',
    name: 'Cana-de-açúcar',
    growTimeSeconds: 60,
    harvestYield: 2,
    xp: 10,
    minLevel: 3,
    icon: '🎋',
    color: '#84CC16',
    growStages: ['🌱', '🎋', '🎋'],
  },
  soybean: {
    id: 'soybean',
    name: 'Soja',
    growTimeSeconds: 90,
    harvestYield: 2,
    xp: 14,
    minLevel: 4,
    icon: '🌱',
    color: '#22C55E',
    growStages: ['🌱', '🌿', '🌱'],
  },
  pumpkin: {
    id: 'pumpkin',
    name: 'Abóbora',
    growTimeSeconds: 150,
    harvestYield: 2,
    xp: 22,
    minLevel: 6,
    icon: '🎃',
    color: '#EA580C',
    growStages: ['🌱', '🪴', '🎃'],
  },
  apple: {
    id: 'apple',
    name: 'Maçã',
    growTimeSeconds: 180,
    harvestYield: 3,
    xp: 28,
    minLevel: 5,
    icon: '🍎',
    color: '#EF4444',
    growStages: ['🌳', '🌸', '🍎'],
  },
};

export const ANIMAL_PENS: Record<string, AnimalPenDef> = {
  chicken: {
    type: 'chicken',
    name: 'Galinha',
    icon: '🐔',
    penName: 'Galinheiro',
    feedId: 'chicken_feed',
    produceId: 'egg',
    produceTimeSeconds: 20,
    xp: 3,
    maxAnimalsPerPen: 3,
    cost: 50,
    minLevel: 1,
  },
  cow: {
    type: 'cow',
    name: 'Vaca',
    icon: '🐮',
    penName: 'Pasto de Vacas',
    feedId: 'cow_feed',
    produceId: 'milk',
    produceTimeSeconds: 45,
    xp: 6,
    maxAnimalsPerPen: 3,
    cost: 150,
    minLevel: 2,
  },
  pig: {
    type: 'pig',
    name: 'Porco',
    icon: '🐷',
    penName: 'Chiqueiro',
    feedId: 'pig_feed',
    produceId: 'bacon',
    produceTimeSeconds: 80,
    xp: 12,
    maxAnimalsPerPen: 3,
    cost: 300,
    minLevel: 5,
  },
  sheep: {
    type: 'sheep',
    name: 'Ovelha',
    icon: '🐑',
    penName: 'Cercado de Ovelhas',
    feedId: 'sheep_feed',
    produceId: 'wool',
    produceTimeSeconds: 120,
    xp: 18,
    maxAnimalsPerPen: 3,
    cost: 600,
    minLevel: 7,
  },
};

export const BUILDINGS: Record<string, BuildingDef> = {
  bakery: {
    type: 'bakery',
    name: 'Padaria',
    icon: '🥖',
    cost: 50,
    minLevel: 1,
    description: 'Assa pães, broas, biscoitos e tortas.',
    baseQueueSlots: 3,
  },
  feed_mill: {
    type: 'feed_mill',
    name: 'Moinho de Ração',
    icon: '⚙️',
    cost: 30,
    minLevel: 1,
    description: 'Produz rações para todos os animais da fazenda.',
    baseQueueSlots: 3,
  },
  dairy: {
    type: 'dairy',
    name: 'Laticínios',
    icon: '🧀',
    cost: 180,
    minLevel: 3,
    description: 'Transforma leite em creme, manteiga e queijo.',
    baseQueueSlots: 3,
  },
  sugar_mill: {
    type: 'sugar_mill',
    name: 'Engenho de Açúcar',
    icon: '🏭',
    cost: 250,
    minLevel: 3,
    description: 'Processa cana em açúcar mascavo, branco e xarope.',
    baseQueueSlots: 3,
  },
  popcorn_pot: {
    type: 'popcorn_pot',
    name: 'Pipoqueira',
    icon: '🍿',
    cost: 380,
    minLevel: 4,
    description: 'Estoura pipocas quentinhas e amanteigadas.',
    baseQueueSlots: 3,
  },
  bbq_grill: {
    type: 'bbq_grill',
    name: 'Churrasqueira / Fogão',
    icon: '🍳',
    cost: 500,
    minLevel: 5,
    description: 'Prepara panquecas, ovos com bacon e hambúrgueres.',
    baseQueueSlots: 3,
  },
  honey_extractor: {
    type: 'honey_extractor',
    name: 'Melzeiro (Extrator de Mel)',
    icon: '🍯⚙️',
    cost: 12500,
    minLevel: 30,
    description: 'Converte favos de néctar fresco em potes de mel puro.',
    baseQueueSlots: 3,
  },
  lure_maker: {
    type: 'lure_maker',
    name: 'Fábrica de Iscas',
    icon: '🧵',
    cost: 15000,
    minLevel: 25,
    description: 'Produz iscas, redes e armadilhas para pesca.',
    baseQueueSlots: 3,
  },
  smelter: {
    type: 'smelter',
    name: 'Fundição',
    icon: '🔥🏭',
    cost: 12500,
    minLevel: 24,
    description: 'Funde minérios extraídos da mina em barras sólidas de ferro, prata e ouro.',
    baseQueueSlots: 3,
  },
};

export const BEE_TREE_CONFIG = {
  cost: 20000,
  minLevel: 30,
  maxTrees: 1,
  maxNectar: 100,
  stages: [
    { stage: 1, bees: 5, upgradeCost: 0, desc: '1 Colmeia (5 Abelhas)' },
    { stage: 2, bees: 10, upgradeCost: 5000, desc: '2 Colmeias (10 Abelhas)' },
    { stage: 3, bees: 15, upgradeCost: 10000, desc: '3 Colmeias (15 Abelhas)' },
    { stage: 4, bees: 20, upgradeCost: 18000, desc: '4 Colmeias (20 Abelhas)' },
    { stage: 5, bees: 25, upgradeCost: 30000, desc: '5 Colmeias (25 Abelhas - Máximo)' },
  ],
};

export const NECTAR_BUSH_CONFIG = {
  cost: 1200,
  minLevel: 30,
  maxNectar: 200,
  width: 1,
  height: 1,
};

export const RECIPES: Recipe[] = [
  // Feed Mill
  {
    id: 'chicken_feed',
    name: 'Ração de Galinha',
    building: 'feed_mill',
    produceTimeSeconds: 15,
    xp: 2,
    ingredients: [{ itemId: 'wheat', count: 2 }],
    minLevel: 1,
  },
  {
    id: 'cow_feed',
    name: 'Ração de Vaca',
    building: 'feed_mill',
    produceTimeSeconds: 25,
    xp: 4,
    ingredients: [
      { itemId: 'corn', count: 1 },
      { itemId: 'wheat', count: 2 },
    ],
    minLevel: 2,
  },
  {
    id: 'pig_feed',
    name: 'Ração de Porco',
    building: 'feed_mill',
    produceTimeSeconds: 40,
    xp: 6,
    ingredients: [
      { itemId: 'carrot', count: 1 },
      { itemId: 'soybean', count: 1 },
    ],
    minLevel: 5,
  },
  {
    id: 'sheep_feed',
    name: 'Ração de Ovelha',
    building: 'feed_mill',
    produceTimeSeconds: 60,
    xp: 8,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'sugarcane', count: 1 },
    ],
    minLevel: 7,
  },

  // Bakery
  {
    id: 'bread',
    name: 'Pão',
    building: 'bakery',
    produceTimeSeconds: 20,
    xp: 4,
    ingredients: [{ itemId: 'wheat', count: 3 }],
    minLevel: 1,
  },
  {
    id: 'corn_bread',
    name: 'Pão de Milho',
    building: 'bakery',
    produceTimeSeconds: 45,
    xp: 8,
    ingredients: [
      { itemId: 'corn', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    minLevel: 2,
  },
  {
    id: 'cookie',
    name: 'Biscoito',
    building: 'bakery',
    produceTimeSeconds: 60,
    xp: 12,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
      { itemId: 'brown_sugar', count: 1 },
    ],
    minLevel: 3,
  },
  {
    id: 'carrot_pie',
    name: 'Torta de Cenoura',
    building: 'bakery',
    produceTimeSeconds: 80,
    xp: 16,
    ingredients: [
      { itemId: 'carrot', count: 3 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    minLevel: 4,
  },
  {
    id: 'pizza',
    name: 'Pizza',
    building: 'bakery',
    produceTimeSeconds: 120,
    xp: 25,
    ingredients: [
      { itemId: 'wheat', count: 2 },
      { itemId: 'cheese', count: 1 },
      { itemId: 'bacon', count: 1 },
    ],
    minLevel: 7,
  },

  // Dairy
  {
    id: 'cream',
    name: 'Nata / Creme',
    building: 'dairy',
    produceTimeSeconds: 30,
    xp: 5,
    ingredients: [{ itemId: 'milk', count: 1 }],
    minLevel: 3,
  },
  {
    id: 'butter',
    name: 'Manteiga',
    building: 'dairy',
    produceTimeSeconds: 50,
    xp: 9,
    ingredients: [{ itemId: 'milk', count: 2 }],
    minLevel: 4,
  },
  {
    id: 'cheese',
    name: 'Queijo',
    building: 'dairy',
    produceTimeSeconds: 80,
    xp: 15,
    ingredients: [{ itemId: 'milk', count: 3 }],
    minLevel: 5,
  },

  // Sugar Mill
  {
    id: 'brown_sugar',
    name: 'Açúcar Mascavo',
    building: 'sugar_mill',
    produceTimeSeconds: 30,
    xp: 4,
    ingredients: [{ itemId: 'sugarcane', count: 1 }],
    minLevel: 3,
  },
  {
    id: 'white_sugar',
    name: 'Açúcar Branco',
    building: 'sugar_mill',
    produceTimeSeconds: 55,
    xp: 7,
    ingredients: [{ itemId: 'sugarcane', count: 2 }],
    minLevel: 4,
  },
  {
    id: 'syrup',
    name: 'Xarope Doce',
    building: 'sugar_mill',
    produceTimeSeconds: 90,
    xp: 14,
    ingredients: [{ itemId: 'sugarcane', count: 4 }],
    minLevel: 6,
  },

  // Popcorn Pot
  {
    id: 'popcorn',
    name: 'Pipoca',
    building: 'popcorn_pot',
    produceTimeSeconds: 30,
    xp: 4,
    ingredients: [{ itemId: 'corn', count: 2 }],
    minLevel: 4,
  },
  {
    id: 'butter_popcorn',
    name: 'Pipoca Amanteigada',
    building: 'popcorn_pot',
    produceTimeSeconds: 60,
    xp: 12,
    ingredients: [
      { itemId: 'corn', count: 2 },
      { itemId: 'butter', count: 1 },
    ],
    minLevel: 5,
  },

  // BBQ Grill
  {
    id: 'pancake',
    name: 'Panquecas',
    building: 'bbq_grill',
    produceTimeSeconds: 45,
    xp: 10,
    ingredients: [
      { itemId: 'egg', count: 1 },
      { itemId: 'brown_sugar', count: 1 },
    ],
    minLevel: 4,
  },
  {
    id: 'bacon_and_eggs',
    name: 'Ovos com Bacon',
    building: 'bbq_grill',
    produceTimeSeconds: 70,
    xp: 18,
    ingredients: [
      { itemId: 'egg', count: 2 },
      { itemId: 'bacon', count: 2 },
    ],
    minLevel: 5,
  },
  {
    id: 'burger',
    name: 'Hambúrguer',
    building: 'bbq_grill',
    produceTimeSeconds: 100,
    xp: 24,
    ingredients: [
      { itemId: 'bread', count: 2 },
      { itemId: 'bacon', count: 1 },
    ],
    minLevel: 6,
  },

  // Honey Extractor (Melzeiro)
  {
    id: 'honey',
    name: 'Pote de Mel Puro',
    building: 'honey_extractor',
    produceTimeSeconds: 45,
    xp: 28,
    ingredients: [{ itemId: 'nectar', count: 4 }],
    minLevel: 30,
  },

  // Lure Maker (Fábrica de Iscas)
  {
    id: 'red_lure',
    name: 'Isca Vermelha',
    building: 'lure_maker',
    produceTimeSeconds: 60,
    xp: 15,
    ingredients: [{ itemId: 'bread', count: 1 }],
    minLevel: 25,
  },
  {
    id: 'green_lure',
    name: 'Isca Verde',
    building: 'lure_maker',
    produceTimeSeconds: 120,
    xp: 25,
    ingredients: [{ itemId: 'corn', count: 2 }],
    minLevel: 25,
  },
  {
    id: 'fishing_net',
    name: 'Rede de Pesca',
    building: 'lure_maker',
    produceTimeSeconds: 300,
    xp: 50,
    ingredients: [
      { itemId: 'wool', count: 3 },
      { itemId: 'wood_plank', count: 1 },
    ],
    minLevel: 25,
  },
  {
    id: 'shrimp_trap',
    name: 'Armadilha p/ Camarão',
    building: 'lure_maker',
    produceTimeSeconds: 400,
    xp: 60,
    ingredients: [
      { itemId: 'wood_plank', count: 2 },
      { itemId: 'nail', count: 1 },
    ],
    minLevel: 25,
  },

  // Fishing Foods
  {
    id: 'sushi',
    name: 'Sushi de Salmão',
    building: 'bakery',
    produceTimeSeconds: 200,
    xp: 35,
    ingredients: [
      { itemId: 'salmon', count: 1 },
      { itemId: 'wheat', count: 3 }, // Substitute for rice
    ],
    minLevel: 25,
  },
  {
    id: 'fish_pie',
    name: 'Torta de Peixe',
    building: 'bakery',
    produceTimeSeconds: 180,
    xp: 30,
    ingredients: [
      { itemId: 'fish_fillet', count: 2 },
      { itemId: 'wheat', count: 2 },
      { itemId: 'egg', count: 1 },
    ],
    minLevel: 25,
  },
  {
    id: 'shrimp_skewer',
    name: 'Espeto de Camarão',
    building: 'bbq_grill',
    produceTimeSeconds: 150,
    xp: 28,
    ingredients: [
      { itemId: 'shrimp', count: 3 },
      { itemId: 'wood_plank', count: 1 }, // Used as skewer stick
    ],
    minLevel: 25,
  },
  // Smelter Recipes
  {
    id: 'iron_bar',
    name: 'Barra de Ferro',
    building: 'smelter',
    produceTimeSeconds: 120, // 2 minutes
    xp: 15,
    ingredients: [
      { itemId: 'iron_ore', count: 3 },
    ],
    minLevel: 24,
  },
  {
    id: 'silver_bar',
    name: 'Barra de Prata',
    building: 'smelter',
    produceTimeSeconds: 180, // 3 minutes
    xp: 24,
    ingredients: [
      { itemId: 'silver_ore', count: 3 },
    ],
    minLevel: 27,
  },
  {
    id: 'gold_bar',
    name: 'Barra de Ouro',
    building: 'smelter',
    produceTimeSeconds: 240, // 4 minutes
    xp: 35,
    ingredients: [
      { itemId: 'gold_ore', count: 3 },
    ],
    minLevel: 30,
  },
];

export const DECORATIONS: Record<string, DecorationDef> = {
  fence_wood: {
    type: 'fence_wood',
    name: 'Cerca Rústica',
    icon: '🪵',
    cost: 15,
    minLevel: 1,
    width: 1,
    height: 1,
  },
  flower_red: {
    type: 'flower_red',
    name: 'Canteiro de Rosas',
    icon: '🌹',
    cost: 25,
    minLevel: 1,
    width: 1,
    height: 1,
  },
  flower_yellow: {
    type: 'flower_yellow',
    name: 'Girassóis',
    icon: '🌻',
    cost: 30,
    minLevel: 2,
    width: 1,
    height: 1,
  },
  hay_bale: {
    type: 'hay_bale',
    name: 'Fardo de Feno',
    icon: '🟨',
    cost: 40,
    minLevel: 2,
    width: 1,
    height: 1,
  },
  scarecrow: {
    type: 'scarecrow',
    name: 'Espantalho Amigável',
    icon: '🧑‍🌾',
    cost: 100,
    minLevel: 3,
    width: 1,
    height: 1,
  },
  apple_tree: {
    type: 'apple_tree',
    name: 'Macieira Florida',
    icon: '🌳🍎',
    cost: 160,
    minLevel: 5,
    width: 1,
    height: 1,
  },
  windmill: {
    type: 'windmill',
    name: 'Moinho de Vento',
    icon: '🌬️',
    cost: 350,
    minLevel: 4,
    width: 2,
    height: 2,
  },
  tractor: {
    type: 'tractor',
    name: 'Trator Clássico Vermelho',
    icon: '🚜',
    cost: 800,
    minLevel: 6,
    width: 2,
    height: 2,
  },
};

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_harvest',
    title: 'Mãos na Terra',
    description: 'Colha 20 lavouras na sua fazenda.',
    icon: '🌾',
    target: 20,
    current: 0,
    rewardCoins: 50,
    rewardGems: 2,
    claimed: false,
  },
  {
    id: 'master_harvest',
    title: 'Rei da Colheita',
    description: 'Colha 100 lavouras na sua fazenda.',
    icon: '🚜',
    target: 100,
    current: 0,
    rewardCoins: 250,
    rewardGems: 5,
    claimed: false,
  },
  {
    id: 'animal_friend',
    title: 'Amigo dos Bichos',
    description: 'Colete 15 produtos de animais (ovos, leite, etc).',
    icon: '🐔',
    target: 15,
    current: 0,
    rewardCoins: 100,
    rewardGems: 3,
    claimed: false,
  },
  {
    id: 'truck_driver',
    title: 'Caminhoneiro da Rota',
    description: 'Entregue 10 pedidos no quadro de encomendas.',
    icon: '🚚',
    target: 10,
    current: 0,
    rewardCoins: 200,
    rewardGems: 4,
    claimed: false,
  },
  {
    id: 'master_chef',
    title: 'Chef do Campo',
    description: 'Produza 20 alimentos nas instalações.',
    icon: '🍞',
    target: 20,
    current: 0,
    rewardCoins: 150,
    rewardGems: 3,
    claimed: false,
  },
  {
    id: 'tycoon',
    title: 'Fazendeiro Próspero',
    description: 'Acumule um total de 1.000 moedas.',
    icon: '💰',
    target: 1000,
    current: 0,
    rewardCoins: 300,
    rewardGems: 10,
    claimed: false,
  },
];

export const INITIAL_ENTITIES: FarmEntity[] = [
  // Farmhouse
  {
    id: 'farmhouse',
    x: 6,
    y: 2,
    width: 2,
    height: 2,
    type: 'farmhouse',
  },
  // Silo
  {
    id: 'silo',
    x: 9,
    y: 2,
    width: 1,
    height: 2,
    type: 'silo',
  },
  // Barn
  {
    id: 'barn',
    x: 11,
    y: 2,
    width: 2,
    height: 2,
    type: 'barn',
  },
  // Order Board
  {
    id: 'order_board',
    x: 4,
    y: 4,
    width: 1,
    height: 1,
    type: 'order_board',
  },
  // Roadside Shop
  {
    id: 'roadside_shop',
    x: 2,
    y: 4,
    width: 2,
    height: 1,
    type: 'roadside_shop',
  },
  // Lucky Wheel Truck
  {
    id: 'lucky_wheel',
    x: 1,
    y: 2,
    width: 2,
    height: 1,
    type: 'lucky_wheel',
  },

  // Starter Crop Plots (6 plots)
  {
    id: 'plot_1',
    x: 5,
    y: 7,
    width: 1,
    height: 1,
    type: 'crop_plot',
    cropData: { cropId: 'wheat', plantedAt: Date.now() - 6000, growDuration: 10 },
  },
  {
    id: 'plot_2',
    x: 6,
    y: 7,
    width: 1,
    height: 1,
    type: 'crop_plot',
    cropData: { cropId: 'wheat', plantedAt: Date.now() - 9000, growDuration: 10 },
  },
  {
    id: 'plot_3',
    x: 7,
    y: 7,
    width: 1,
    height: 1,
    type: 'crop_plot',
    cropData: { cropId: 'corn', plantedAt: Date.now() - 5000, growDuration: 25 },
  },
  {
    id: 'plot_4',
    x: 5,
    y: 8,
    width: 1,
    height: 1,
    type: 'crop_plot',
    cropData: { cropId: null, plantedAt: null, growDuration: 0 },
  },
  {
    id: 'plot_5',
    x: 6,
    y: 8,
    width: 1,
    height: 1,
    type: 'crop_plot',
    cropData: { cropId: null, plantedAt: null, growDuration: 0 },
  },
  {
    id: 'plot_6',
    x: 7,
    y: 8,
    width: 1,
    height: 1,
    type: 'crop_plot',
    cropData: { cropId: null, plantedAt: null, growDuration: 0 },
  },

  // Starter Chicken Coop
  {
    id: 'chicken_coop_1',
    x: 9,
    y: 6,
    width: 2,
    height: 2,
    type: 'animal_pen',
    animalData: {
      animalType: 'chicken',
      animals: [
        { id: 'c1', fedAt: Date.now() - 15000, isReady: false },
        { id: 'c2', fedAt: null, isReady: false },
        { id: 'c3', fedAt: null, isReady: false },
      ],
    },
  },

  // Starter Bakery
  {
    id: 'bakery_1',
    x: 3,
    y: 9,
    width: 2,
    height: 2,
    type: 'building',
    buildingData: {
      buildingType: 'bakery',
      queueSlots: 3,
      queue: [],
      completedItems: [],
    },
  },

  // Starter Feed Mill
  {
    id: 'feed_mill_1',
    x: 9,
    y: 9,
    width: 2,
    height: 2,
    type: 'building',
    buildingData: {
      buildingType: 'feed_mill',
      queueSlots: 3,
      queue: [],
      completedItems: [],
    },
  },

  // Starter Scarecrow decoration
  {
    id: 'scarecrow_1',
    x: 4,
    y: 7,
    width: 1,
    height: 1,
    type: 'decoration',
    decorationType: 'scarecrow',
  },
  // Starter Obstacles (dead trees and dead bushes to clear)
  {
    id: 'dead_tree_1',
    x: 12,
    y: 8,
    width: 1,
    height: 1,
    type: 'dead_tree',
  },
  {
    id: 'dead_tree_2',
    x: 2,
    y: 11,
    width: 1,
    height: 1,
    type: 'dead_tree',
  },
  {
    id: 'dead_bush_1',
    x: 14,
    y: 10,
    width: 1,
    height: 1,
    type: 'dead_bush',
  },
  {
    id: 'dead_bush_2',
    x: 4,
    y: 12,
    width: 1,
    height: 1,
    type: 'dead_bush',
  },
];
